### ISSUE TITLE
Exceptions encountered

### ISSUE THREAD

**Issue by Masamune3210** [LukeFZ/CikExtractor#2]
Parsing registry entries...
Registry loaded.
Deriving device key...
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\Registry\Registry.py", line 385, in __init__
    self._buf = filelikeobject.read()
AttributeError: 'str' object has no attribute 'read'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\qiling\os\windows\registry.py", line 178, in __init__
    self.reghive = RegHive(hivedir)
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\qiling\os\windows\registry.py", line 89, in __init__
    'SECURITY' : __make_reg('SECURITY'),
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\qiling\os\windows\registry.py", line 85, in __make_reg
    return Registry.Registry(os.path.join(hname, kname))
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\Registry\Registry.py", line 387, in __init__
    with open(filelikeobject, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Users\\User\\Downloads\\CikExtractor-v1.0.1\\Emulation\\x8664_windows\\Windows\\registry\\SECURITY'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\User\Downloads\CikExtractor-v1.0.1\Emulation\clep_vault.py", line 40, in <module>
    ql = Qiling(["./clipsp.sys"], ".\\x8664_windows", libcache=True, console=False)
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\qiling\core.py", line 178, in __init__
    self._os = select_os(ostype)(self)
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\qiling\os\windows\windows.py", line 91, in __init__
    self.load()
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\qiling\os\windows\windows.py", line 129, in load
    self.__setup_components()
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\qiling\os\windows\windows.py", line 164, in __setup_components
    self.registry_manager = registry.RegistryManager(self.ql, reghive)
  File "C:\Users\User\AppData\Roaming\Python\Python310\site-packages\qiling\os\windows\registry.py", line 181, in __init__
    raise QlErrorFileNotFound("Windows registry hive not found")
qiling.exception.QlErrorFileNotFound: Windows registry hive not found
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at CikExtractor.DeviceKeyDumper.DeriveDeviceKey(Byte[] smbios, Byte[] driveSerial, Byte[] encryptedLicense) in M:\DevEnvironment\DevWorkspace\dotNETProjects\CIKExtractor\CikExtractor\DeviceKeyDumper.cs:line 69
   at CikExtractor.DeviceKeyDumper.DumpDeviceKey(Byte[] encryptedLicense) in M:\DevEnvironment\DevWorkspace\dotNETProjects\CIKExtractor\CikExtractor\DeviceKeyDumper.cs:line 12
   at CikExtractor.Program.Main(String[] args) in M:\DevEnvironment\DevWorkspace\dotNETProjects\CIKExtractor\CikExtractor\Program.cs:line 12

**Comment by LukeFZ** [comment]
Looks like CikExtractor failed to dump the required registry hives, since its complaining about the SECURITY hive missing. You can check the contents of `D:\Users\User\Downloads\CikExtractor-v1.0.1\Emulation\x8664_windows\Windows\registry\` to see if this is actually the issue, or if there is another issue at play here.

If the directory does not contain all required registry hives (SYSTEM, SECURITY, SOFTWARE, HARDWARE, SAM, NTUSER.DAT) you can try and delete the entire "registry" directory and rerun the program, and it should attempt to dump the hives again. If that didn't work, you can dump them manually using the `reg save HKLM\<hive name> <output path>` command (except for NTUSER.DAT, you have to copy that from `C:\Users\Default\NTUSER.DAT`)

**Comment by Masamune3210** [comment]
.\Emulation\x8664_windows\registry is just a empty folder

**Comment by Masamune3210** [comment]
It worked after completely deleting the cikextractor folder and re-extracting from the release zip, thanks

**Comment by LukeFZ** [comment]
👍
