### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Sanches8002** [LukeFZ/CikExtractor#7]
I'm using Python 3.12.6, Qiling 1.4.6 and Windows 10

INFO: Loading entries from registry...
INFO: Registry loaded.
INFO: Deriving device key...
[=]     Initiate stack address at 0x7ffffffde000
[=]     Loading ./clipsp.sys to 0x1c0000000
[=]     PE entry point at 0x1c01111f0
[=]     DriverObject is at 0x6000000
[=]     RegistryPath is at 0x6000150
Traceback (most recent call last):
  File "C:\CIK\Emulation\clep_vault.py", line 40, in <module>
    ql = Qiling(["./clipsp.sys"], ".\\x8664_windows", libcache=True, console=False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanch\AppData\Roaming\Python\Python312\site-packages\qiling\core.py", line 195, in __init__
    self.loader.run()
  File "C:\Users\sanch\AppData\Roaming\Python\Python312\site-packages\qiling\loader\pe.py", line 725, in run
    self.load(pe)
  File "C:\Users\sanch\AppData\Roaming\Python\Python312\site-packages\qiling\loader\pe.py", line 758, in load
    self.ql.arch.regs.write(UC_X86_REG_CR8, 0)
  File "C:\Users\sanch\AppData\Roaming\Python\Python312\site-packages\qiling\arch\register.py", line 69, in write
    return self.uc.reg_write(register, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sanch\AppData\Local\Programs\Python\Python312\Lib\site-packages\unicorn\unicorn_py3\arch\intel.py", lin
e 177, in reg_write
    super().reg_write(reg_id, value)
  File "C:\Users\sanch\AppData\Local\Programs\Python\Python312\Lib\site-packages\unicorn\unicorn_py3\unicorn.py", line 4
21, in reg_write
    self._reg_write(reg_id, self._DEFAULT_REGTYPE, value)
  File "C:\Users\sanch\AppData\Local\Programs\Python\Python312\Lib\site-packages\unicorn\unicorn_py3\unicorn.py", line 3
77, in _reg_write
    raise UcError(status, reg_id)
unicorn.unicorn_py3.unicorn.UcError: Invalid argument (UC_ERR_ARG)
Error: Object reference not set to an instance of an object.

Is there any fix?

**Comment by LukeFZ** [comment]
Should be fixed by no longer using Qiling for emulation.
