### ISSUE TITLE
Get same error

### ISSUE THREAD

**Issue by mo1234-web** [LukeFZ/CikExtractor#8]
Traceback (most recent call last):
  File "C:\Users\ma123\Downloads\CikExtractor\Emulation\clep_vault.py", line 40, in <module>
    ql = Qiling(["./clipsp.sys"], ".\\x8664_windows", libcache=True, console=False)
  File "C:\Users\ma123\AppData\Local\Programs\Python\Python313\Lib\site-packages\qiling\core.py", line 223, in __init__
    self.loader.run()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\ma123\AppData\Local\Programs\Python\Python313\Lib\site-packages\qiling\loader\pe.py", line 506, in run
    self.load()
    ~~~~~~~~~^^
  File "C:\Users\ma123\AppData\Local\Programs\Python\Python313\Lib\site-packages\qiling\loader\pe.py", line 577, in load
    self.ql.reg.write(UC_X86_REG_CR8, 0)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ma123\AppData\Local\Programs\Python\Python313\Lib\site-packages\qiling\arch\register.py", line 73, in write
    return self.ql.uc.reg_write(register, value)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\ma123\AppData\Local\Programs\Python\Python313\Lib\site-packages\unicorn\unicorn_py3\arch\intel.py", line 177, in reg_write
    super().reg_write(reg_id, value)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\ma123\AppData\Local\Programs\Python\Python313\Lib\site-packages\unicorn\unicorn_py3\unicorn.py", line 437, in reg_write
    self._reg_write(reg_id, self._DEFAULT_REGTYPE, value)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ma123\AppData\Local\Programs\Python\Python313\Lib\site-packages\unicorn\unicorn_py3\unicorn.py", line 393, in _reg_write
    raise UcError(status, reg_id)
unicorn.unicorn_py3.unicorn.UcError: Invalid argument (UC_ERR_ARG)
Error: Object reference not set to an instance of an object.

**Comment by LukeFZ** [comment]
Should be fixed by no longer using Qiling for emulation.
